#initial and start postgresql server
- name: Install base packages
  yum:
    name: "{{ packages }}"
    state: latest



- name: Create directories for postgresql
  file: path={{ item }} state=directory owner=postgresql group=postgresql
  with_items:
    - "{{ package_dir }}"
    - "{{ shelldir }}"
    - "{{ monitordir }}"
    - "{{ basedir }}"
    - "{{ datadir }}"
    - "{{ etcdir }}"
    - "{{ logdir }}"
    - "{{ masterdir }}"

- name: Copy postgresql compressed package
  copy:
    src: "{{ package_name }}"
    dest: "{{ package_dir }}"

- name: Uncompress postgresql package to package dir
  unarchive:
    src: "{{ package_dir }}/{{ package_name }}"
    dest: "{{ package_dir }}/"
    remote_src: yes

- name: Copy uncompressed package
  copy:
    src: "{{ package_dir }}/{{ postgresql_version }}/"
    dest: "{{ basedir }}"
    remote_src: yes

# - name: Chown privileges for volume directories
#   file: path="{{ basedir }}" owner=postgresql group=postgresql recurse=yes

- name: Add the postgresql execution path to the environment variable
  lineinfile:
    path: /etc/profile
    line: export PATH={{ basedir }}/bin:$PATH
    insertafter: EOF
    state: present

- name: Source profile
  shell: "source /etc/profile"

- name: Rendering postgresql parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: postgresql
    group: postgresql
    mode: 0644
  with_items:
    - { src: 'postgresql.conf.j2', dest: '/usr/lib/tmpfiles.d/postgresql.conf' }
    - { src: 'postgresqld.service.j2', dest: '/usr/lib/systemd/system/postgresqld_{{ postgresql_port }}.service' }
    - { src: 'my.cnf.j2', dest: "{{ etcdir }}/my_{{ postgresql_port }}.cnf" }

- name: Rendering postgresql5.7 parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: postgresql
    group: postgresql
    mode: 0644
  with_items:
    - { src: 'postgresql.conf.j2', dest: '/usr/lib/tmpfiles.d/postgresql.conf' }
    - { src: 'postgresqld.service57.j2', dest: '/usr/lib/systemd/system/postgresqld_{{ postgresql_port }}.service' }
    - { src: 'my.cnf57.j2', dest: "{{ etcdir }}/my_{{ postgresql_port }}.cnf" }
  when: postgresql57 | default(False)

- name: Rendering bash file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - { src: 'my.cnf_auto.sh.j2', dest: "{{ etcdir }}/my.cnf_auto.sh" }
    - { src: 'see_log.sh.j2', dest: "{{ shelldir }}/see_log_{{ postgresql_port }}.sh" }
    - { src: 'asynchronous_connection_failover.sh.j2', dest: "{{ shelldir }}/asynchronous_connection_failover.sh" }

- name: Auto config my.cnf
  shell: "sudo sh -x {{ etcdir }}/my.cnf_auto.sh"

- name: Remove my.cnf_auto.sh
  file:
    path: "{{ etcdir }}/my.cnf_auto.sh"
    state: absent
    remote_src: yes

# - name: Obtain user_whitelist
#   shell: "sudo cat /tmp/user_whitelist.txt"
#   register: user_whitelist

- name: Initial postgresql server
  shell: "sudo {{ item }}"
  with_items:
    - "{{ basedir }}/bin/postgresqld --defaults-file={{ etcdir }}/my_{{ postgresql_port }}.cnf --user=postgresql --lower-case-table-names=1 \
    --initialize-insecure --basedir={{ basedir }} --datadir={{ datadir }}"
    - "{{ basedir }}/bin/postgresql_ssl_rsa_setup --datadir={{ datadir }}"

- name: Clean system's buffer and cache
  sysctl:
    name: vm.drop_caches
    value: '1'
    state: present

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Start postgresql server
  systemd:
    name: postgresqld_{{ postgresql_port }}
    state: started

- name: Enable postgresql server
  systemd:
    name: postgresqld_{{ postgresql_port }}
    enabled: yes

- name: Wait for postgresql is running
  pause: seconds=7

- name: Create a symbolic link for "/tmp/postgresql.sock"
  file:
    src: "{{ datadir }}/postgresql.sock"
    dest: /tmp/postgresql.sock
    state: link

- name: Modify root password
  postgresql_user:
    login_user: root
    login_password:
    login_host: localhost
    name: root
    password: "{{ root_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add root@127.0.0.1 user 
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: root
    password: "{{ root_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: "127.0.0.1"
    priv: '*.*:ALL,GRANT'
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add remote root user
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: root
    password: "{{ root_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: "{{ ansible_default_ipv4.network }}/24"
    priv: '*.*:ALL,GRANT'
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add repl user
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: repl
    password: "{{ postgresql_monitor_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: "%"
    priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT,Execute,Process/PERFORMANCE_SCHEMA.*:SELECT/SYS.*:SELECT'
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add pmm user
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: pmm
    password: "{{ pmm_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: 127.0.0.1
    priv: '*.*:SELECT,RELOAD,PROCESS,SUPER,REPLICATION CLIENT/PERFORMANCE_SCHEMA.*:SELECT,UPDATE,DELETE,DROP'
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add audit user
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: audit
    password: "{{ postgresql_monitor_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: "{{ ansible_default_ipv4.network }}/24"
    priv: '*.*:REPLICATION SLAVE,SUPER,REPLICATION CLIENT'
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add business user
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: "{{ business_user }}"
    password: "{{ business_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: "{{ ansible_default_ipv4.network }}/24"
    priv: "{{ business_user }}.*:SELECT,UPDATE,DELETE,INSERT"
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Add global read only user
  postgresql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: global
    password: "{{ read_only_password }}"
    update_password: always
    login_port: "{{ postgresql_port }}"
    host: "{{ ansible_default_ipv4.network }}/24"
    priv: "*.*:SELECT"
    sql_log_bin: no
    login_unix_socket: "{{ socket }}"
    state: present

- name: Case sensitive password string match for logining postgresql
  expect:
    command: "{{ basedir }}/bin/postgresql_config_editor set --login-path=postgresql_{{ postgresql_port }} --host=127.0.0.1 -P {{ postgresql_port }} --user=root --password"
    responses:
      (?i)password: "{{ root_password }}"
      (?i)Continue: y
    echo: yes
  no_log: True

- name: Copy the mgr_monitor.sql
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}/"
  with_items:
    - { src: 'mgr_monitor_official.sql', dest: "{{ shelldir }}/" }

- name: Rendering the check.sql
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'check.sql.j2', dest: "{{ shelldir }}/check.sql" }

- name: Execute mgr_monitor.sql
  shell: "sudo {{ basedir }}/bin/postgresql --login-path=postgresql_{{ postgresql_port }} < {{ shelldir }}/mgr_monitor_official.sql"

- name: Add logrotate for postgresql error log
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - { src: 'postgresql.j2', dest: '/etc/logrotate.d/postgresql_{{ postgresql_port }}'}

- name: Add the job of logrotate for msyql error log
  cron:
    name: "postgresql_{{ postgresql_port }} logrotate"
    weekday: "6"
    minute: "55"
    hour: "23"
    job: "/usr/sbin/logrotate -vf -s /var/lib/logrotate/logrotate.status /etc/logrotate.d/postgresql_{{ postgresql_port }} > /dev/null 2>&1 &"

# - name: Set some parameters
#   postgresql_variables:
#     login_user: root
#     login_password: "{{ root_password }}"
#     login_port: "{{ postgresql_port }}"
#     login_unix_socket: "{{ socket }}"
#     variable: "{{ item.original }}"
#     value: "{{ item.change }}"
#   with_items:
#     #- { original: 'rpl_semi_sync_slave_enabled', change: '1' }
#     #- { original: 'rpl_semi_sync_master_enabled', change: '1' }
#     #- { original: 'rpl_semi_sync_master_timeout', change: '500' } #兼容8.0.25
#     - { original: 'clone_enable_compression', change: '1' }
#     #- { original: 'group_replication_start_on_boot', change: '1' }
#     #目前组复制节点被操作系统KILL后再自动启动加入组复制会导致整个组复制无PRIMARY或者其他问题，需要人工介入修复，故不建议随postgresql启动
#   when: not postgresql57

# - name: Modify semisync parameter and clone parameter in my.cnf
#   replace:
#     path: "{{ etcdir }}/my_{{ postgresql_port }}.cnf"
#     regexp: "{{ item.original }}"
#     replace: "{{ item.change }}"
#   with_items:
#     #- { original: '#rpl_semi_sync_slave_enabled = 1', change: 'rpl_semi_sync_slave_enabled = 1' }
#     #- { original: '#rpl_semi_sync_master_enabled = 1', change: 'rpl_semi_sync_master_enabled = 1' }
#     #- { original: '#rpl_semi_sync_master_timeout = 500', change: 'rpl_semi_sync_master_timeout = 500' }#兼容8.0.25
#     - { original: '#clone_enable_compression = 1', change: 'clone_enable_compression = 1' }
#     #- { original: 'loose-group_replication_start_on_boot = off', change: 'loose-group_replication_start_on_boot = on' }
#   when: not postgresql57
